# Generated by Django 4.2.5 on 2023-11-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Elimination Status'),
        ),
    ]
