# Generated by Django 4.2.5 on 2023-11-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0003_rubric_survivor_advantages_survivor_confessionals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='fanFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
