# Generated by Django 4.2.5 on 2023-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0004_survivor_fanfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
