# Generated by Django 4.2.5 on 2023-11-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0007_season_rubric_season_survivor_season_team_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='idols_tie_split',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='immunities_tie_split',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='fan_favorite_negative_votes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rubric',
            name='fan_favorite_self_votes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rubric',
            name='fan_favorite_share_votes',
            field=models.BooleanField(default=True, verbose_name="Whether fan favorite vote for this season includes all linked seasons' votes, or just its own"),
        ),
    ]
