# Generated by Django 4.2.5 on 2023-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0010_alter_season_rubric"),
    ]

    operations = [
        migrations.AddField(
            model_name="survivor",
            name="placement",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="survivor",
            name="status",
            field=models.BooleanField(
                default=False,
                verbose_name="Elimination Status - False for eliminated, True for surviving",
            ),
        ),
    ]
