# Generated by Django 4.2.5 on 2023-12-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0011_survivor_placement_alter_survivor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='pic',
            field=models.ImageField(default=False, null=True, upload_to=''),
        ),
    ]
