# Generated by Django 4.2.5 on 2023-12-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0012_survivor_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survivor",
            name="pic",
            field=models.ImageField(default=False, null=True, upload_to="survivor"),
        ),
    ]
