# Generated by Django 4.2.5 on 2023-12-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0013_alter_survivor_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="survivor",
            name="tribe",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
