# Generated by Django 4.2.5 on 2023-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0014_survivor_tribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='pic_full',
            field=models.ImageField(default=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='pic',
            field=models.ImageField(default=False, null=True, upload_to=''),
        ),
    ]
