# Generated by Django 4.2.5 on 2023-12-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0017_remove_survivor_fan_favorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="survivor",
            name="fan_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
