# Generated by Django 4.2.5 on 2023-12-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0018_survivor_fan_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_close',
            field=models.DateField(null=True),
        ),
    ]
