# Generated by Django 4.2.5 on 2024-01-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0023_alter_team_captain_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='survivor_drafting',
            field=models.BooleanField(default=False),
        ),
    ]
