# Generated by Django 4.2.5 on 2024-03-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0027_remove_survivor_team_survivor_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="survivor",
            name="season",
        ),
        migrations.AddField(
            model_name="survivor",
            name="season",
            field=models.ManyToManyField(
                to="survive.season", verbose_name="a season a Survivor belongs to"
            ),
        ),
    ]
