# Generated by Django 4.2.5 on 2024-03-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0030_alter_survivor_season_alter_survivor_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='team_creation',
            field=models.BooleanField(default=True),
        ),
    ]
