# Generated by Django 4.2.5 on 2024-03-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0031_season_team_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='linked_seasons',
            field=models.ManyToManyField(blank=True, default=None, to='survive.season', verbose_name='The other seasons this season is associated with'),
        ),
    ]
