# Generated by Django 4.2.5 on 2024-03-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0032_season_linked_seasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="draft_marker",
            field=models.IntegerField(
                default=1,
                verbose_name="Number representing the spot in the draft, with 1 being the first draft & going up from there",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="draft_order",
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name="Comma-delimited list of positions this team can draft in",
            ),
        ),
    ]
