# Generated by Django 4.2.5 on 2024-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0039_rubric_pity_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="managed_season",
            field=models.BooleanField(
                default=True,
                verbose_name="True if season is managed by a draft owner Team",
            ),
        ),
        migrations.AlterField(
            model_name="rubric",
            name="pity_point",
            field=models.IntegerField(
                default=0,
                verbose_name="Points awarded to the first eliminated survivor.",
            ),
        ),
    ]
