# Generated by Django 4.2.5 on 2024-05-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0040_season_managed_season_alter_rubric_pity_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="managed_season",
            field=models.BooleanField(
                default=True,
                verbose_name="Managed Season: true if season is managed by a draft owner Team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="draft_owner",
            field=models.BooleanField(
                default=False,
                verbose_name="Draft Owner: whether this Team has administrative access to the draft & draft ordering",
            ),
        ),
    ]
