# Generated by Django 4.2.5 on 2024-05-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0041_alter_season_managed_season_alter_team_draft_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="season_close",
            field=models.DateField(null=True, verbose_name="Season Close"),
        ),
        migrations.AlterField(
            model_name="season",
            name="season_open",
            field=models.DateField(null=True, verbose_name="Season Open"),
        ),
        migrations.AlterField(
            model_name="season",
            name="survivor_drafting",
            field=models.BooleanField(default=False, verbose_name="Survivor Drafting"),
        ),
        migrations.AlterField(
            model_name="season",
            name="team_creation",
            field=models.BooleanField(default=True, verbose_name="Team Creation"),
        ),
    ]
