# Generated by Django 4.2.5 on 2024-05-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0042_alter_season_season_close_alter_season_season_open_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="season_close",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Season Close"
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="season_open",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Season Open"
            ),
        ),
    ]
