# Generated by Django 4.2.5 on 2024-05-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survive", "0043_alter_season_season_close_alter_season_season_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="rubric",
            name="name",
            field=models.CharField(
                default="Rubric",
                max_length=100,
                verbose_name="A name to identify this rubric by.",
            ),
        ),
        migrations.AlterField(
            model_name="rubric",
            name="confessionals_tie_split",
            field=models.BooleanField(
                default=True,
                verbose_name="Whether ties in most confessionals split points. True means points are split, False means each survivor is rewarded the maximum value.",
            ),
        ),
        migrations.AlterField(
            model_name="rubric",
            name="fan_favorite_share_votes",
            field=models.BooleanField(
                default=True,
                verbose_name="Whether fan favorite vote for this season includes all linked seasons' votes, or just its own. True includes linked season votes, False does not.",
            ),
        ),
    ]
