# Generated by Django 4.2.5 on 2025-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0047_team_prediction_survivors_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='pic',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='pic_full',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
