# Generated by Django 4.2.5 on 2026-06-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survive', '0048_alter_survivor_pic_alter_survivor_pic_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='date_value',
            field=models.IntegerField(default=0, null=True, verbose_name='The points awarded per date that a Love Overboard contestant participated in.'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='lower_deck_to_upper_deck_value',
            field=models.IntegerField(default=0, null=True, verbose_name='The points awarded per times that a contestant moved from the lower deck to the upper deck.'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='sex_value',
            field=models.IntegerField(default=0, null=True, verbose_name='The points awarded per times that a contestant woohooed.'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='upper_deck_to_lower_deck_value',
            field=models.IntegerField(default=0, null=True, verbose_name='The points awarded per times that a contestant moved from the upper deck to a lower deck (may be negative).'),
        ),
    ]
